name: Push to Windows VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy to Host Directory
      run: powershell Copy-Item -Path C:\Users\763606-su\actions-runner\_work\VirtualMachineTesting\* -Destination C:\inetpub\wwwroot -force
